# Generated by Django 3.2.7 on 2021-09-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('construction', models.CharField(max_length=30, verbose_name='Конструкция')),
                ('brand', models.CharField(max_length=30, verbose_name='Брэнд')),
                ('RMS_power', models.CharField(max_length=10, verbose_name='Мощность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Имя категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarphonesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('construction', models.CharField(max_length=30, verbose_name='Конструкция')),
                ('brand', models.CharField(max_length=30, verbose_name='Брэнд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Имя категории')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
